### ISSUE TITLE
Request to add another dataset (ClimateSet)

### ISSUE THREAD

**Issue by liellnima** [shengchaochen82/Awesome-Foundation-Models-for-Weather-and-Climate#4]
Hi there,

thank you for providing such a comprehensive overview of foundational models for weather and climate! I really appreciate the work you have put in there. 

I wanted to ask if you think ClimateSet ([Website](https://climateset.github.io/), [Paper Link](https://arxiv.org/abs/2311.03721)) could be an addition to your dataset collection? (Disclaimer: I am one of the authors). If you don't think it fits in your list / survey, don't worry, I just wanted to let you know in case you haven't seen it so far and would like to add it :) 

Cheers,
Julia

**Comment by liellnima** [comment]
Also [ClimateBench](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2021MS002954) might be an interesting addition for you! All of this goes more into the direction of climate projection though

**Comment by shengchaochen82** [comment]
Hi Julia,

Thank you for you advice. ClimateSet is indeed a remarkable work, presenting a high-quality dataset. It has been incorporated into our latest paper. I apologize for the oversight in not promptly updating it in the repository.

I have now updated both ClimateSet and ClimateBench in the repository. Furthermore, I plan to make additional updates to this work ^ ^. Thanks once again!

Warm regard,

Shengchao

**Comment by liellnima** [comment]
Thank you so much! Looking forward to your future work :D
